server:
  port: 80
spring:
  # thymeleaf
  thymeleaf:
    cache: false
    encoding: UTF-8
  #  redis
  redis:
    host: 192.168.136.129
    port: 6379
  # cache
  cache:
    type: redis
  mvc:
    hiddenmethod:
      filter:
        enabled: true

